
package rs_midtest.client.rs_midtest.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "HelloWorldWebServiceService", targetNamespace = "http://service.rs_midtest/", wsdlLocation = "http://127.0.0.1:456/helloworld?wsdl")
public class HelloWorldWebServiceService
    extends Service
{

    private final static URL HELLOWORLDWEBSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException HELLOWORLDWEBSERVICESERVICE_EXCEPTION;
    private final static QName HELLOWORLDWEBSERVICESERVICE_QNAME = new QName("http://service.rs_midtest/", "HelloWorldWebServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:456/helloworld?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        HELLOWORLDWEBSERVICESERVICE_WSDL_LOCATION = url;
        HELLOWORLDWEBSERVICESERVICE_EXCEPTION = e;
    }

    public HelloWorldWebServiceService() {
        super(__getWsdlLocation(), HELLOWORLDWEBSERVICESERVICE_QNAME);
    }

    public HelloWorldWebServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), HELLOWORLDWEBSERVICESERVICE_QNAME, features);
    }

    public HelloWorldWebServiceService(URL wsdlLocation) {
        super(wsdlLocation, HELLOWORLDWEBSERVICESERVICE_QNAME);
    }

    public HelloWorldWebServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, HELLOWORLDWEBSERVICESERVICE_QNAME, features);
    }

    public HelloWorldWebServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HelloWorldWebServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns HelloWorldWebService
     */
    @WebEndpoint(name = "HelloWorldWebServicePort")
    public HelloWorldWebService getHelloWorldWebServicePort() {
        return super.getPort(new QName("http://service.rs_midtest/", "HelloWorldWebServicePort"), HelloWorldWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HelloWorldWebService
     */
    @WebEndpoint(name = "HelloWorldWebServicePort")
    public HelloWorldWebService getHelloWorldWebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.rs_midtest/", "HelloWorldWebServicePort"), HelloWorldWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (HELLOWORLDWEBSERVICESERVICE_EXCEPTION!= null) {
            throw HELLOWORLDWEBSERVICESERVICE_EXCEPTION;
        }
        return HELLOWORLDWEBSERVICESERVICE_WSDL_LOCATION;
    }

}
